name: Lychee PR external linkcheck
on:
  pull_request:
    branches:
      - main
jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      - name: Run Lychee Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: --config lychee.toml ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Comment Broken Links
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: lychee/out.md

      - name: Report Status
        if: failure()
        run: echo "❌ Broken links detected. Please fix them!"
