name: Webhook
on:
   workflow_dispatch: 
jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      name: post
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.WFADDRESS }}
        headers: '{"Authorization": "${{ secrets.WFAUTH }}" }'
        body: '{"event": "deployment", "repository": "joelwmale/webhook-action"}'
        github_event_payload: true
