name: Webhook
on:
   workflow_dispatch: 
jobs:
  post-data:
    runs-on: ubuntu-latest

    steps:
      - name: post2
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WFADDRESS }}
          webhook_auth_type: "header"
          webhook_auth: "Authorization: ${{ secrets.WFAUTH }}"
      - name: post
        uses: joelwmale/webhook-action@cc1a66f987e1591785273fd6f9d2f7a9d8d7c9cd
        with:
          url: ${{ secrets.WFADDRESS }}
          headers: '{"Authorization": "${{ secrets.WFAUTH }}" }'
          body: '{"event": "deployment", "repository": "joelwmale/webhook-action"}'
          github_event_payload: true
